import type { Metadata } from "next";
import {
  Merriweather,
  Montserrat,
  Ubuntu_Mono,
} from "next/font/google";
import Script from "next/script";
import "./globals.css";

const fontSans = Montserrat({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const fontSerif = Merriweather({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-merriweather",
  weight: ["300", "400", "700", "900"],
});

const fontMono = Ubuntu_Mono({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-ubuntu-mono",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable}`}
    >
      <body className="antialiased">
        <Script id="theme-init" strategy="beforeInteractive">
          {`(() => {
            const storedTheme = localStorage.getItem("theme");
            const theme = storedTheme === "light" || storedTheme === "dark"
              ? storedTheme
              : window.matchMedia("(prefers-color-scheme: dark)").matches
                ? "dark"
                : "light";
            document.documentElement.classList.toggle("dark", theme === "dark");
          })();`}
        </Script>
        {children}
      </body>
    </html>
  );
}
